### ISSUE TITLE
getting repetition time

### ISSUE THREAD

**Issue by naxir121** [paulmueller/PyScanFCS#5]
Dear Paul,

We tried to use your program for perpendicular scanning FCS on an Olympus system. However, I could not manage to find the repetition time so that I can see the correct time-intensity trace. We scan usually 50*1 pixel, 10um pixel dwell time. 
Is there some pre-settings that we need to consider while scanning the line (such as 512*1 pixel, scanning time etc.)
Best,
Erdinc.

**Comment by paulmueller** [comment]
...as it does not seem to be PyScanFCS-related.
